services:
  flask:
    build: ./flask
    container_name: flask_app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./flask/app/static/:/static/:ro
    depends_on:
      - flask