services:
  flask:
    build: ./flask
    container_name: flask_app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./flask/app/static/:/static/:ro
      - /etc/letsencrypt/live/topstylebykatenoda.com:/etc/letsencrypt/live/topstylebykatenoda.com:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
      - /var/www/html:/var/www/html
    depends_on:
      - flask