# Generated by Django 3.2.6 on 2021-12-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='images')),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
    ]
