# Generated by Django 3.2.6 on 2021-12-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20211211_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail_pic1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail_pic2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail_pic3',
        ),
    ]
