# Generated by Django 3.2.6 on 2022-03-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_product_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
