# Generated by Django 3.2.6 on 2022-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottomShelf',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='topShelf',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
