# Generated by Django 3.2.6 on 2022-03-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stylists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
