# Generated by Django 3.2.6 on 2021-11-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='stylist',
        ),
        migrations.AddField(
            model_name='service',
            name='number_of_prices',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='price_explanation_one',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='price_explanation_three',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='price_explanation_two',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='price_one',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='price_three',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='price_two',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='subtext',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
