# Generated by Django 3.2.6 on 2021-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20211112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_explanation_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_explanation_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_explanation_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
