# Generated by Django 3.2.6 on 2021-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Cutting', 'Cutting'), ('Coloring', 'Coloring'), ('Bridal', 'Bridal'), ('Extra', 'Extra')], default='Cutting', max_length=10),
        ),
    ]
