# Generated by Django 3.2.6 on 2021-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_image',
            name='is_duplicate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='gallery_image',
            name='category',
            field=models.CharField(blank=True, choices=[('Cutting', 'Cutting'), ('Coloring', 'Coloring'), ('Bridal', 'Bridal'), ('Extra', 'Extra')], default='Cutting', max_length=10),
        ),
    ]
